name: poc_flutter_empty
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  go_router: ^6.5.6
  http: ^0.13.5
  result_dart: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
